line-length = 120
target-version = "py312"

[format]
docstring-code-format = true

[lint]
select = ["ALL"]
ignore = [
    "COM812",   # Trailing comma missing
    "D1",       # undocumented
    "D213",     # multi-line summary second line
    "D400",     # first line should end with a period
    "ERA001",   # ignore detection of commented-out code
    "FBT001",   # Allow boolean positional value in function definition (flake8-boolean-trap)
    "FBT002",   # Allow boolean positional value in function definition (flake8-boolean-trap)
    "TD001",    # invalid todo tag
    "TD002",    # missing todo author
    "TD003",    # missing todo link
    "T201",     # allow use of print statement
    "I001",     # import block is un-sorted or un-formatted
    "INP001",   # file does not exist
    "S101",     # use of assert statement
    "ANN101",   # missing type annotation for self in method
    "ANN102",   # missing type annotation for cls in classmethod
    "PGH003",   # Allow use of blanket-type-ignore comments
    "PLR0913",  # too many arguments in function definition
    "PLR2004",  # magic value used in comparison
    "PTH123",   # ignore path operation rule
    "RUF001",   # allow unicode string normalization issues
    "RUF002",   # allow ambiguous unicode character names
    "RUF003",   # allow ambiguous unicode character usage
]
unfixable = [
    "F841", # unused variable
]

[lint.isort]
force-wrap-aliases = true
lines-after-imports = 2
known-first-party = ["app"]